// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBElg0WtT60KVJOE2pLSr6_YRT6np9JEIs',
    appId: '1:693054823449:web:d74ff73ef5ba1b30705e88',
    messagingSenderId: '693054823449',
    projectId: 'ayam-petelur-web',
    authDomain: 'ayam-petelur-web.firebaseapp.com',
    storageBucket: 'ayam-petelur-web.firebasestorage.app',
    measurementId: 'G-30BLZNCCXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVP8uu9b2VL4C1sY_CJ4bnTrIELHRzljQ',
    appId: '1:693054823449:android:935501ec9479f978705e88',
    messagingSenderId: '693054823449',
    projectId: 'ayam-petelur-web',
    storageBucket: 'ayam-petelur-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcMRA_oumYDXk3ZlxTq_aUyc-4BwiIL_c',
    appId: '1:693054823449:ios:2aa0e33e1f461ccc705e88',
    messagingSenderId: '693054823449',
    projectId: 'ayam-petelur-web',
    storageBucket: 'ayam-petelur-web.firebasestorage.app',
    iosBundleId: 'com.example.ayamPetelurWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcMRA_oumYDXk3ZlxTq_aUyc-4BwiIL_c',
    appId: '1:693054823449:ios:2aa0e33e1f461ccc705e88',
    messagingSenderId: '693054823449',
    projectId: 'ayam-petelur-web',
    storageBucket: 'ayam-petelur-web.firebasestorage.app',
    iosBundleId: 'com.example.ayamPetelurWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBElg0WtT60KVJOE2pLSr6_YRT6np9JEIs',
    appId: '1:693054823449:web:1d65a55296c5edd0705e88',
    messagingSenderId: '693054823449',
    projectId: 'ayam-petelur-web',
    authDomain: 'ayam-petelur-web.firebaseapp.com',
    storageBucket: 'ayam-petelur-web.firebasestorage.app',
    measurementId: 'G-FCZFHZRTNK',
  );
}
